FROM python:3.10

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    google-genai \
    pydantic

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "5000"]
